version: "3"
services:
  postgres:
    image: postgres:13.1-alpine
    network_mode: bridge
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres
  springbootapp:
    image: docker-spring-boot-postgres:latest
    build:
      context: .
    network_mode: bridge
    container_name: app-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    links:
      - postgres