SELECT U.*,
	TRAINING_ID,
	TRAINING_DATE,
	COUNT(TRAINING_ID) count
FROM public.user U
JOIN TRAINING_DETAILS T ON U.USER_ID = T.USER_ID
GROUP BY U.USER_ID,
	U.USERNAME,
	T.TRAINING_DATE,
	T.TRAINING_DATE,
	T.TRAINING_ID
HAVING COUNT(T.TRAINING_ID) > 1
ORDER BY T.TRAINING_DATE DESC